
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyBook Hype AMD
 */
public class Dosen extends javax.swing.JFrame {
   String userLevel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public Dosen(String level) {
        initComponents();
        this.userLevel = level;
        tampilkanData(); 
        kosongkanForm();
        otomatisKode();
        setLocationRelativeTo(null);
    }
    public Dosen() {
        initComponents();
    }
private void otomatisKode() {
    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        // Ambil kode_dosen terakhir
        String sql = "SELECT kode_dosen FROM dosen ORDER BY kode_dosen DESC LIMIT 1";
        java.sql.ResultSet r = s.executeQuery(sql);

        if (r.next()) {
            String lastKode = r.getString("kode_dosen");
            // Mengambil angka setelah huruf "D" (index ke-1 ke atas)
            int nomor = Integer.parseInt(lastKode.substring(1)) + 1;
            String kode = String.format("D%03d", nomor);
            txtKode.setText(kode);
        } else {
            // Jika tabel kosong
            txtKode.setText("D001");
        }
    } catch (Exception e) {
        txtKode.setText("D001");
    }
}
private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Dosen");
    model.addColumn("Nama Dosen");
    model.addColumn("Jabatan");

    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        java.sql.ResultSet r = s.executeQuery("SELECT * FROM dosen");

        while (r.next()) {
            model.addRow(new Object[]{
                r.getString("kode_dosen"),
                r.getString("nama_dosen"),
                r.getString("jabatan")
            });
        }
        tbDosen.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Load Tabel: " + e.getMessage());
    }
}
private void kosongkanForm() {
    // 1. Generate kode dosen otomatis yang baru
    otomatisKode(); 
    
    // 2. Kosongkan field nama dosen
    txtDosen.setText("");
    
    // 3. Reset ComboBox ke pilihan pertama (index 0)
    cbJabatan.setSelectedIndex(0);
    
    // 4. Supaya kode bisa diisi lagi (jika sebelumnya false pas klik tabel)
    txtKode.setEditable(true);
    
    // 5. Fokuskan kursor ke Nama Dosen
    txtDosen.requestFocus(); 
}
public void isiDataDariFind(String kode, String nama, String jabatan) {
    txtKode.setText(kode);
    txtDosen.setText(nama);
    cbJabatan.setSelectedItem(jabatan);

    // Update tampilan tabel agar hanya menampilkan satu hasil yang dicari
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Dosen");
    model.addColumn("Nama Dosen");
    model.addColumn("Jabatan");
    model.addRow(new Object[]{kode, nama, jabatan});
    tbDosen.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDosen = new javax.swing.JLabel();
        Kode = new javax.swing.JLabel();
        Dosen = new javax.swing.JLabel();
        Jabatan = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtDosen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDosen = new javax.swing.JTable();
        jMahasiswa2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cbJabatan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDosen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDosen.setText("DATA DOSEN");

        Kode.setText("Kode Dosen");

        Dosen.setText("Nama Dosen");

        Jabatan.setText("Jabatan");

        tbDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode_Dosen", "Nama_Dosen", "Jabatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDosen);

        jMahasiswa2.setText("DATA YANG SUDAH DIINPUT");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepala Prodi", "Dosen Wali", "Dosen" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMahasiswa2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInsert)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFind)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClose)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kode)
                                    .addComponent(Dosen)
                                    .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDosen)
                                    .addComponent(txtKode, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(cbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jDosen)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kode)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosen)
                    .addComponent(txtDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jabatan)
                    .addComponent(cbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jMahasiswa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        new FindDosen().setVisible(true);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new MenuUtama(userLevel).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tbDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDosenMouseClicked
        int baris = tbDosen.getSelectedRow();
    
    String kode = tbDosen.getValueAt(baris, 0).toString();
    String nama = tbDosen.getValueAt(baris, 1).toString();
    String jabatan = tbDosen.getValueAt(baris, 2).toString();
    
    txtKode.setText(kode);
    txtDosen.setText(nama);
    cbJabatan.setSelectedItem(jabatan); // Set ComboBox sesuai data tabel
    
    txtKode.setEditable(false); // Biar kode kunci tidak diganti saat update
    }//GEN-LAST:event_tbDosenMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        String sql = "INSERT INTO dosen (kode_dosen, nama_dosen, jabatan) VALUES (?, ?, ?)";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        p.setString(1, txtKode.getText());
        p.setString(2, txtDosen.getText());
        p.setString(3, cbJabatan.getSelectedItem().toString()); // Ambil data dari ComboBox
        
        p.executeUpdate();
        p.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Disimpan!");
        tampilkanData(); // Panggil method refresh tabel
        kosongkanForm(); // Panggil method reset input
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        String sql = "UPDATE dosen SET nama_dosen = ?, jabatan = ? WHERE kode_dosen = ?";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        p.setString(1, txtDosen.getText());
        p.setString(2, cbJabatan.getSelectedItem().toString());
        p.setString(3, txtKode.getText()); // Kode dosen sebagai kunci
        
        p.executeUpdate();
        p.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Diperbarui!");
        tampilkanData();
        kosongkanForm();
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data " + txtKode.getText() + "?", 
            "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection c = config.Koneksi.getKoneksi();
            String sql = "DELETE FROM dosen WHERE kode_dosen = ?";
            java.sql.PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, txtKode.getText());
            
            p.executeUpdate();
            p.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            tampilkanData();
            kosongkanForm();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dosen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dosen;
    private javax.swing.JLabel Jabatan;
    private javax.swing.JLabel Kode;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JLabel jDosen;
    private javax.swing.JLabel jMahasiswa2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDosen;
    private javax.swing.JTextField txtDosen;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables
}
