
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MyBook Hype AMD
 */
public class FormNilaiArray extends javax.swing.JFrame {

    String userLevel;
    String[][] dataMahasiswa = new String[5][6];
    int jumlahData = 0; // Untuk melacak sudah berapa data yang diinput
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilaiArray.class.getName());
    private final DefaultTableModel model;

    /**
     * Creates new form FormNilaiArray
     */
    public FormNilaiArray(String level) { // Tambahkan parameter String level
        initComponents();
        this.userLevel = level; // PERBAIKAN: Simpan kiriman level ke variabel class
        model = (DefaultTableModel) tbNilai.getModel();
        tampilkanData();
    }

    public FormNilaiArray() {
        initComponents();
        this.userLevel = "";
        model = (DefaultTableModel) tbNilai.getModel();
        tampilkanData();
    }

    private void tampilkanData() {
        model.setRowCount(0);
        try {
            Connection c = config.Koneksi.getKoneksi();
            String sql;
            PreparedStatement p;

            if (txtNim.getText().equals("")) {
                // Tambahkan nama_mk di SELECT
                sql = "SELECT nim, nama_mk, uts, tugas, uas, absen, nilai_akhir FROM nilai";
                p = c.prepareStatement(sql);
            } else {
                sql = "SELECT nim, nama_mk, uts, tugas, uas, absen, nilai_akhir FROM nilai WHERE nim = ?";
                p = c.prepareStatement(sql);
                p.setString(1, txtNim.getText());
            }

            java.sql.ResultSet r = p.executeQuery();
            while (r.next()) {
                model.addRow(new Object[]{
                    r.getString("nim"),
                    r.getString("nama_mk"), // Ambil data mata kuliah dari database
                    r.getDouble("uts"),
                    r.getDouble("tugas"),
                    r.getDouble("uas"),
                    r.getDouble("absen"),
                    r.getString("nilai_akhir")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Uts = new javax.swing.JLabel();
        Tugas = new javax.swing.JLabel();
        Uas = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        txtUts = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtUas = new javax.swing.JTextField();
        txtAbsen = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtJudul2 = new javax.swing.JLabel();
        txtJudul1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNilai = new javax.swing.JTable();
        pMahasiswa = new javax.swing.JPanel();
        Matkul = new javax.swing.JLabel();
        Nim = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        cbMatkul = new javax.swing.JComboBox<>();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Uts.setText("Nilai UTS");

        Tugas.setText("Nilai Tugas");

        Uas.setText("Nilai UAS");

        Absen.setText("Nilai Absensi");

        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtJudul2.setText("DATA YANG SUDAH DIINPUT");

        txtJudul1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul1.setText("FORM NILAI");

        tbNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Mata Kuliah", "UTS", "Tugas", "UAS", "Absensi", "Nilai Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbNilai);

        pMahasiswa.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        Matkul.setText("Mata Kuliah");

        Nim.setText("NIM");

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMahasiswaLayout = new javax.swing.GroupLayout(pMahasiswa);
        pMahasiswa.setLayout(pMahasiswaLayout);
        pMahasiswaLayout.setHorizontalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Matkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMahasiswaLayout.createSequentialGroup()
                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFind))
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMahasiswaLayout.setVerticalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Matkul)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Uas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Uts, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Absen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 341, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInput)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnClose))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(txtJudul1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(pMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtJudul1)
                .addGap(22, 22, 22)
                .addComponent(pMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Uts))
                    .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Tugas))
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Uas))
                    .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Absen))
                    .addComponent(txtAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInput)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear)
                        .addComponent(btnClose)
                        .addComponent(btnDelete)))
                .addGap(26, 26, 26)
                .addComponent(txtJudul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        try {
            // 1. Ambil data dari inputan
            String nim = txtNim.getText();
            String matkul = cbMatkul.getSelectedItem().toString(); // Ambil matkul yang dipilih
            double uts = Double.parseDouble(txtUts.getText());
            double tugas = Double.parseDouble(txtTugas.getText());
            double uas = Double.parseDouble(txtUas.getText());
            double absen = Double.parseDouble(txtAbsen.getText());

            // Hitung Nilai Akhir sesuai format bapak dosen (30%, 20%, 40%, 10%)
            double na = (uts * 0.3) + (tugas * 0.2) + (uas * 0.4) + (absen * 0.1);

            // 3. Tentukan Grade (ini yang bakal jadi "Nilai Akhir" kamu)
            String grade;
            if (na >= 85) {
                grade = "A";
            } else if (na >= 75) {
                grade = "B";
            } else if (na >= 65) {
                grade = "C";
            } else if (na >= 50) {
                grade = "D";
            } else {
                grade = "E";
            }

            // 4. Simpan ke Database (Kolom nilai_akhir diisi huruf grade)
            Connection c = config.Koneksi.getKoneksi();
            String sql = "INSERT INTO nilai (nim, nama_mk, uts, tugas, uas, absen, nilai_akhir) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);

            p.setString(1, nim);      // 1. nim (String)
            p.setString(2, matkul);   // 2. nama_mk (String)
            p.setDouble(3, uts);      // 3. uts (Double)
            p.setDouble(4, tugas);    // 4. tugas (Double)
            p.setDouble(5, uas);      // 5. uas (Double)
            p.setDouble(6, absen);    // 6. absen (Double) 
            p.setString(7, grade);    // 7. nilai_akhir (String/Grade A,B,C)

            p.executeUpdate();
            tampilkanData();

            // Bersihkan field setelah input (Opsional biar rapi)
            txtUts.setText("");
            txtTugas.setText("");
            txtUas.setText("");
            txtAbsen.setText("");

            // Notifikasi hanya sukses simpan saja, gak usah sebut Grade-nya
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtNim.setText("");
        cbMatkul.removeAllItems(); // Opsional: bersihkan juga daftar matkul
        txtUts.setText("");
        txtTugas.setText("");
        txtUas.setText("");
        txtAbsen.setText("");
        tampilkanData();

        // Kembalikan kursor ke kotak NIM
        txtNim.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new MenuUtama(userLevel).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String nim = txtNim.getText();

        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan NIM terlebih dahulu!");
            tampilkanData();
            return;
        }

        cbMatkul.removeAllItems(); // Bersihkan isi combo box sebelumnya

        try {
            Connection c = config.Koneksi.getKoneksi();
            // Query untuk mengambil nama matkul berdasarkan NIM melalui tabel KRS
            // Kita gunakan JOIN agar bisa dapat Nama Mata Kuliah-nya
            String sql = "SELECT m.nama_mk FROM krs k "
                    + "JOIN mata_kuliah m ON k.kode_mk = m.kode_mk "
                    + "WHERE k.nim = ?";

            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nim);
            java.sql.ResultSet r = p.executeQuery();

            boolean ditemukan = false;
            while (r.next()) {
                cbMatkul.addItem(r.getString("nama_mk"));
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "NIM tidak ditemukan atau tidak mengontrak KRS!");
            } else {
                JOptionPane.showMessageDialog(this, "Data KRS ditemukan!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat KRS: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int barisTerpilih = tbNilai.getSelectedRow();

        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Klik dulu baris di tabel yang mau dihapus!");
            return;
        }

        // Ambil NIM dari kolom ke-0 dan Mata Kuliah dari kolom ke-1
        String nimDihapus = tbNilai.getValueAt(barisTerpilih, 0).toString();
        String matkulDihapus = tbNilai.getValueAt(barisTerpilih, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Hapus nilai " + matkulDihapus + " untuk NIM " + nimDihapus + "?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection c = config.Koneksi.getKoneksi();

                // Hapus berdasarkan NIM DAN Mata Kuliah supaya spesifik 1 baris
                String sql = "DELETE FROM nilai WHERE nim = ? AND nama_mk = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nimDihapus);
                p.setString(2, matkulDihapus);

                int result = p.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                    tampilkanData();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilaiArray().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Matkul;
    private javax.swing.JLabel Nim;
    private javax.swing.JLabel Tugas;
    private javax.swing.JLabel Uas;
    private javax.swing.JLabel Uts;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInput;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pMahasiswa;
    private javax.swing.JTable tbNilai;
    private javax.swing.JTextField txtAbsen;
    private javax.swing.JLabel txtJudul1;
    private javax.swing.JLabel txtJudul2;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
