
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MyBook Hype AMD
 */
public class Krs extends javax.swing.JFrame {

    String userLevel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Krs.class.getName());
    private final DefaultTableModel model;

    /**
     * Creates new form Krs
     */
    public Krs(String level) {
        initComponents();
        this.userLevel = level;
        model = (DefaultTableModel) tbKrs.getModel();
        tbKrs.getColumnModel().getColumn(0).setMinWidth(0);
        tbKrs.getColumnModel().getColumn(0).setMaxWidth(0);
        tbKrs.getColumnModel().getColumn(0).setWidth(0);
        tampilkanDataKRS();
        loadComboData();
    }
public Krs() {
        initComponents();
        model = (DefaultTableModel) tbKrs.getModel();
    }
    private void tampilkanDataKRS() {
        model.setRowCount(0);
        try {
            Connection c = config.Koneksi.getKoneksi();
            // Tetap tarik id_krs sebagai identitas unik
            String sql = "SELECT id_krs, kode_mk, mata_kuliah, sks, dosen FROM krs WHERE nim = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, txtNim.getText());
            ResultSet r = p.executeQuery();

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getString("id_krs"), // Indeks 0 (ID)
                    r.getString("kode_mk"), // Indeks 1
                    r.getString("mata_kuliah"), // Indeks 2
                    r.getString("sks"), // Indeks 3
                    r.getString("dosen") // Indeks 4
                });
            }
            updateLabelTotalSks();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private int hitungTotalSksDiTabel() {
        int total = 0;
        for (int i = 0; i < tbKrs.getRowCount(); i++) {
            total += Integer.parseInt(tbKrs.getValueAt(i, 2).toString());
        }
        return total;
    }

    // FUNGSI INI JUGA HARUS DI LUAR
    private void updateLabelTotalSks() {
        int total = hitungTotalSksDiTabel();
        totalSks.setText("Total SKS : " + total);
    }

    private void loadComboData() {
        try {
            Connection c = config.Koneksi.getKoneksi();

            // Load Mata Kuliah
            cbMatkul.removeAllItems();
            cbMatkul.addItem("-- Pilih Mata Kuliah --");
            ResultSet rMatkul = c.createStatement().executeQuery("SELECT nama_mk FROM mata_kuliah");
            while (rMatkul.next()) {
                cbMatkul.addItem(rMatkul.getString("nama_mk"));
            }

            // Load Dosen
            cbDosen.removeAllItems();
            cbDosen.addItem("-- Pilih Dosen --");
            ResultSet rDosen = c.createStatement().executeQuery("SELECT nama_dosen FROM dosen");
            while (rDosen.next()) {
                cbDosen.addItem(rDosen.getString("nama_dosen"));
            }

        } catch (Exception e) {
            System.out.println("Error Load Combo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMahasiswa = new javax.swing.JPanel();
        Nim = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        pMatkul = new javax.swing.JPanel();
        Matkul = new javax.swing.JLabel();
        Sks = new javax.swing.JLabel();
        Dosen = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox<>();
        txtSks = new javax.swing.JTextField();
        cbDosen = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        pKrs = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKrs = new javax.swing.JTable();
        totalSks = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMahasiswa.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        Nim.setText("NIM");

        Nama.setText("Nama");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMahasiswaLayout = new javax.swing.GroupLayout(pMahasiswa);
        pMahasiswa.setLayout(pMahasiswaLayout);
        pMahasiswaLayout.setHorizontalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pMahasiswaLayout.createSequentialGroup()
                        .addComponent(Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMahasiswaLayout.createSequentialGroup()
                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNama)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMahasiswaLayout.setVerticalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pMatkul.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Mata Kuliah"));

        Matkul.setText("Mata Kuliah");

        Sks.setText("SKS");

        Dosen.setText("Dosen");

        cbMatkul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMatkulItemStateChanged(evt);
            }
        });
        cbMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatkulActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMatkulLayout = new javax.swing.GroupLayout(pMatkul);
        pMatkul.setLayout(pMatkulLayout);
        pMatkulLayout.setHorizontalGroup(
            pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMatkulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Matkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pMatkulLayout.createSequentialGroup()
                        .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMatkulLayout.setVerticalGroup(
            pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMatkulLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Matkul)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sks)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosen)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pKrs.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA YANG SUDAH DIINPUT"));

        tbKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode_MK", "Mata Kuliah", "SKS", "Dosen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbKrs);
        if (tbKrs.getColumnModel().getColumnCount() > 0) {
            tbKrs.getColumnModel().getColumn(0).setResizable(false);
        }

        totalSks.setText("Total SKS :");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKrsLayout = new javax.swing.GroupLayout(pKrs);
        pKrs.setLayout(pKrsLayout);
        pKrsLayout.setHorizontalGroup(
            pKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKrsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKrsLayout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        pKrsLayout.setVerticalGroup(
            pKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKrsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalSks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMatkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pKrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pKrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String nim = txtNim.getText().trim();

        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukan NIM");
            return;
        }

        try {
            Connection c = config.Koneksi.getKoneksi();

            // --- STEP 1: CARI NAMA MAHASISWA ---
            String sqlMhs = "SELECT nama FROM mahasiswa WHERE nim = ?";
            PreparedStatement pMhs = c.prepareStatement(sqlMhs);
            pMhs.setString(1, nim);
            ResultSet rMhs = pMhs.executeQuery();

            if (rMhs.next()) {
                txtNama.setText(rMhs.getString("nama"));

                // --- STEP 2: CARI DATA KRS (SEE DATA) ---
                // Kita langsung tampilkan apa saja yang sudah dia ambil di database
                DefaultTableModel model = (DefaultTableModel) tbKrs.getModel();
                model.setRowCount(0); // Bersihkan tabel UI dulu

                String sqlKrs = "SELECT id_krs, kode_mk, mata_kuliah, sks, dosen FROM krs WHERE nim = ?";
                PreparedStatement pKrs = c.prepareStatement(sqlKrs);
                pKrs.setString(1, nim);
                ResultSet rKrs = pKrs.executeQuery();

                boolean adaData = false;
                while (rKrs.next()) {
                    adaData = true;
                    model.addRow(new Object[]{
                        rKrs.getString("id_krs"), // Masukkan ID ke kolom 0
                        rKrs.getString("kode_mk"),
                        rKrs.getString("mata_kuliah"),
                        rKrs.getString("sks"),
                        rKrs.getString("dosen")
                    });
                }

                // Update total SKS di label
                updateLabelTotalSks();

                if (!adaData) {
                    JOptionPane.showMessageDialog(this, "Mahasiswa ditemukan, tapi belum mengambil KRS.");
                }

            } else {
                JOptionPane.showMessageDialog(this, "NIM '" + nim + "' tidak terdaftar di database!");
                txtNama.setText("");
                model.setRowCount(0);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Find: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void cbMatkulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMatkulItemStateChanged
        if (cbMatkul.getSelectedIndex() > 0) {
            try {
                Connection c = config.Koneksi.getKoneksi();
                String sql = "SELECT sks FROM mata_kuliah WHERE nama_mk = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, cbMatkul.getSelectedItem().toString());
                ResultSet r = p.executeQuery();

                if (r.next()) {
                    txtSks.setText(r.getString("sks"));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_cbMatkulItemStateChanged

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            int sksBaru = Integer.parseInt(txtSks.getText());
            int totalSksSekarang = hitungTotalSksDiTabel();

            if (totalSksSekarang + sksBaru > 24) {
                JOptionPane.showMessageDialog(this, "Gagal! Total SKS melebihi batas maksimal 24 SKS.");
            } else {
                Connection c = config.Koneksi.getKoneksi();
                String sql = "SELECT kode_mk FROM mata_kuliah WHERE nama_mk = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, cbMatkul.getSelectedItem().toString());
                ResultSet r = p.executeQuery();
                for (int i = 0; i < tbKrs.getRowCount(); i++) {
                    if (tbKrs.getValueAt(i, 1).toString().equals(cbMatkul.getSelectedItem().toString())) {
                        JOptionPane.showMessageDialog(this, "Mata kuliah ini sudah ada di daftar!");
                        return;
                    }
                }
                if (r.next()) {
                    model.addRow(new Object[]{
                        "",
                        r.getString("kode_mk"),
                        cbMatkul.getSelectedItem(),
                        txtSks.getText(),
                        cbDosen.getSelectedItem()
                    });
                    updateLabelTotalSks();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pilih mata kuliah dulu!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Connection c = config.Koneksi.getKoneksi();
            int rowsSaved = 0;

            for (int i = 0; i < tbKrs.getRowCount(); i++) {
                // Ambil ID untuk mengecek apakah data sudah ada di DB atau belum
                Object idObj = tbKrs.getValueAt(i, 0);

                // KITA HANYA INSERT DATA YANG ID-NYA MASIH KOSONG (DATA BARU)
                if (idObj == null || idObj.toString().trim().isEmpty()) {
                    String sql = "INSERT INTO krs (nim, kode_mk, mata_kuliah, sks, dosen) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement p = c.prepareStatement(sql);

                    p.setString(1, txtNim.getText());           // NIM dari TextField
                    p.setString(2, tbKrs.getValueAt(i, 1).toString()); // Kode MK (Sekarang di Indeks 1)
                    p.setString(3, tbKrs.getValueAt(i, 2).toString()); // Nama MK (Sekarang di Indeks 2)
                    p.setString(4, tbKrs.getValueAt(i, 3).toString()); // SKS (Sekarang di Indeks 3)
                    p.setString(5, tbKrs.getValueAt(i, 4).toString()); // Dosen (Sekarang di Indeks 4)

                    p.executeUpdate();
                    rowsSaved++;
                }
            }

            if (rowsSaved > 0) {
                JOptionPane.showMessageDialog(this, rowsSaved + " Mata kuliah baru berhasil disimpan!");
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data baru untuk disimpan.");
            }

            // REFRESH DATA (Penting agar kolom ID yang tadi kosong jadi terisi dari DB)
            tampilkanDataKRS();

            // Kosongkan inputan matkul saja, NIM jangan dikosongkan agar user bisa lihat hasilnya
            txtSks.setText("");
            cbMatkul.setSelectedIndex(0);
            cbDosen.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMatkulActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new MenuUtama(userLevel).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tbKrs.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang mau dihapus!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin mau hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Ambil ID dari kolom 0 (yang disembunyikan tadi)
                Object idValue = tbKrs.getValueAt(row, 0);

                if (idValue == null || idValue.toString().trim().isEmpty()) {
                    // Data baru di tabel, belum masuk database
                    model.removeRow(row);
                } else {
                    // Data sudah ada di database, hapus berdasarkan ID
                    Connection c = config.Koneksi.getKoneksi();
                    String sql = "DELETE FROM krs WHERE id_krs = ?";
                    PreparedStatement p = c.prepareStatement(sql);
                    p.setString(1, idValue.toString());

                    if (p.executeUpdate() > 0) {
                        model.removeRow(row);
                        JOptionPane.showMessageDialog(this, "Data berhasil dihapus dari database!");
                    }
                }
                updateLabelTotalSks();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saat menghapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Krs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dosen;
    private javax.swing.JLabel Matkul;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nim;
    private javax.swing.JLabel Sks;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pKrs;
    private javax.swing.JPanel pMahasiswa;
    private javax.swing.JPanel pMatkul;
    private javax.swing.JTable tbKrs;
    private javax.swing.JLabel totalSks;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables
}
