
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyBook Hype AMD
 */
public class Mahasiswa extends javax.swing.JFrame {
    String userLevel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa(String level) {
        initComponents();
        this.userLevel = level;
        otomatisNIM();
        kosongkanForm();
        tampilkanData();
        setLocationRelativeTo(null);
    }
    public Mahasiswa() {
        initComponents();
    }
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIM");
    model.addColumn("Nama");
    model.addColumn("Email");

    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        java.sql.ResultSet r = s.executeQuery("SELECT * FROM mahasiswa");

        while (r.next()) {
            model.addRow(new Object[]{
                r.getString("nim"),
                r.getString("nama"),
                r.getString("email")
            });
        }
        tbMahasiswa.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Load Tabel: " + e.getMessage());
    }
}
    private void kosongkanForm() {
    otomatisNIM();
    txtNim.setText("");
    txtNama.setText("");
    txtEmail.setText("");
    txtNama.requestFocus(); // Biar kursor balik ke ID
    }
    private boolean isValidEmail(String email) {
    // Pola standar email: teks + @ + teks + . + teks
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" + 
                        "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    
    java.util.regex.Pattern pat = java.util.regex.Pattern.compile(emailRegex);
    if (email == null)
        return false;
    return pat.matcher(email).matches();
}
    private void otomatisNIM() {
    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        // Ambil NIM terakhir untuk menentukan urutan berikutnya
        String sql = "SELECT nim FROM mahasiswa ORDER BY nim DESC LIMIT 1";
        java.sql.ResultSet r = s.executeQuery(sql);
        
        // Prefix 8 digit pertama (11 digit total - 3 digit urutan)
        String prefix = "24552011"; 

        if (r.next()) {
            String lastNim = r.getString("nim"); 
            
            // Logika: Ambil 3 angka paling belakang, lalu tambah 1
            // Jika NIM = 24552011001, substring(8) akan mengambil "001"
            int nomor = Integer.parseInt(lastNim.substring(8)) + 1;
            
            // Format kembali menjadi 11 digit
            String kode = prefix + String.format("%03d", nomor);
            txtNim.setText(kode);
        } else {
            // Jika tabel kosong, mulai dari urutan 001
            txtNim.setText(prefix + "001");
        }
    } catch (Exception e) {
        // Fallback jika terjadi error pada database atau parsing
        txtNim.setText("24552011001");
    }
}
    public void isiDataDariFind(String nim, String nama, String email) {
    txtNim.setText(nim);
    txtNama.setText(nama);
    txtEmail.setText(email);

    // Update tampilan tabel agar hanya menampilkan hasil pencarian
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("NIM");
    model.addColumn("Nama");
    model.addColumn("Email");
    model.addRow(new Object[]{nim, nama, email});
    tbMahasiswa.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMahasiswa = new javax.swing.JLabel();
        Nim = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();
        jMahasiswa2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMahasiswa.setText("DATA MAHASISWA");

        Nim.setText("NIM");

        Nama.setText("Nama");

        Email.setText("Email");

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });

        tbMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMahasiswa);

        jMahasiswa2.setText("DATA YANG SUDAH DIINPUT");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jMahasiswa))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNim))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNama))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMahasiswa2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInsert)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFind)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClose)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jMahasiswa)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jMahasiswa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        new FindMahasiswa().setVisible(true);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new MenuUtama(userLevel).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String email = txtEmail.getText();

    // 1. Jalankan validasi email
    if (!isValidEmail(email)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Format Email Salah! Contoh: user@gmail.com", 
            "Peringatan", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        txtEmail.requestFocus();
        return; 
    }

    // 2. Jalankan Insert ke Database
    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        // Pastikan nama kolom sesuai: nim, nama, email
        String sql = "INSERT INTO mahasiswa (nim, nama, email) VALUES (?, ?, ?)";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        // Isi parameter sesuai urutan tanda tanya
        p.setString(1, txtNim.getText());
        p.setString(2, txtNama.getText());
        p.setString(3, txtEmail.getText());
        
        p.executeUpdate();
        p.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Penyimpanan Data Berhasil!");
        tampilkanData(); // Refresh tabel agar data baru muncul
        kosongkanForm(); // Reset form dan NIM otomatis baru
        
    } catch (java.sql.SQLException e) {
        // Tampilkan error spesifik dari database agar mudah didebug
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Insert: " + e.getMessage());
    }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!isValidEmail(txtEmail.getText())) {
        JOptionPane.showMessageDialog(this, "Format Email Salah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        txtEmail.requestFocus();
        return;
    }

    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        // Query SQL: Update Nama dan Email berdasarkan NIM
        String sql = "UPDATE mahasiswa SET nama = ?, email = ? WHERE nim = ?";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        p.setString(1, txtNama.getText());
        p.setString(2, txtEmail.getText());
        p.setString(3, txtNim.getText()); // NIM sebagai kunci penentu
        
        p.executeUpdate();
        p.close();
        
        JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
        tampilkanData(); // Refresh tabel
        kosongkanForm(); // Reset form
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data " + txtNim.getText() + "?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection c = config.Koneksi.getKoneksi();
            String sql = "DELETE FROM mahasiswa WHERE nim = ?";
            java.sql.PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, txtNim.getText());
            
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            tampilkanData(); 
            kosongkanForm();
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaMouseClicked
        int baris = tbMahasiswa.getSelectedRow();
    
    // 2. Ambil data dari tabel (urutan kolom: 0=NIM, 1=Nama, 2=Email)
    String nim   = tbMahasiswa.getValueAt(baris, 0).toString();
    String nama  = tbMahasiswa.getValueAt(baris, 1).toString();
    String email = tbMahasiswa.getValueAt(baris, 2).toString();
    
    // 3. Set data ke TextField masing-masing
    txtNim.setText(nim);
    txtNama.setText(nama);
    txtEmail.setText(email);
    
    // 4. Supaya NIM tidak diedit saat Update (karena Primary Key)
    txtNim.setEditable(false);
    }//GEN-LAST:event_tbMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nim;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jMahasiswa;
    private javax.swing.JLabel jMahasiswa2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMahasiswa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
