
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyBook Hype AMD
 */
public class MataKuliah extends javax.swing.JFrame {
    String userLevel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public MataKuliah(String level) {
        initComponents();
        this.userLevel = level;
        otomatisKode();
        kosongkanForm();
        tampilkanData();
        setLocationRelativeTo(null);
    }
    public MataKuliah() {
        initComponents();
    }
private void otomatisKode() {
    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        String sql = "SELECT kode_mk FROM mata_kuliah ORDER BY kode_mk DESC LIMIT 1";
        java.sql.ResultSet r = s.executeQuery(sql);

        if (r.next()) {
            String lastKode = r.getString("kode_mk");
            // Mengambil 3 angka terakhir setelah "MK"
            int nomor = Integer.parseInt(lastKode.substring(2)) + 1;
            String kode = String.format("MK%03d", nomor);
            txtKode.setText(kode);
        } else {
            txtKode.setText("MK001");
        }
    } catch (Exception e) {
        txtKode.setText("MK001");
    }
}
private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Mata Kuliah");
    model.addColumn("Nama Mata Kuliah");
    model.addColumn("SKS");

    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        java.sql.Statement s = c.createStatement();
        java.sql.ResultSet r = s.executeQuery("SELECT * FROM mata_kuliah");

        while (r.next()) {
            model.addRow(new Object[]{
                r.getString("kode_mk"),
                r.getString("nama_mk"),
                r.getString("sks")
            });
        }
        tbMatkul.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Load Tabel: " + e.getMessage());
    }
}
    private void kosongkanForm() {
    // 1. Panggil lagi fungsi otomatis agar kode MK bertambah (misal dari MK001 ke MK002)
    otomatisKode(); 
    
    // 2. Kosongkan field nama mata kuliah dan SKS
    txtMatkul.setText("");
    txtSks.setText("");
    
    // 3. Arahkan kursor langsung ke field Nama Matkul supaya user bisa langsung ngetik lagi
    txtMatkul.requestFocus(); 
}
    public void isiDataDariFind(String kode, String nama, String sks) {
    txtKode.setText(kode);
    txtMatkul.setText(nama);
    txtSks.setText(sks);

    // Update tampilan tabel agar hanya menampilkan hasil pencarian yang dipilih
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Mata Kuliah");
    model.addColumn("Nama Mata Kuliah");
    model.addColumn("SKS");
    model.addRow(new Object[]{kode, nama, sks});
    tbMatkul.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMatkul = new javax.swing.JLabel();
        Kode = new javax.swing.JLabel();
        Matkul = new javax.swing.JLabel();
        SKS = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        txtSks = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMatkul = new javax.swing.JTable();
        jMahasiswa2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMatkul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMatkul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMatkul.setText("DATA MATA KULIAH");

        Kode.setText("Kode Mata Kuliah");

        Matkul.setText("Nama Mata Kuliah");

        SKS.setText("SKS");

        tbMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode_MK", "Nama_MK", "SKS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMatkul);

        jMahasiswa2.setText("DATA YANG SUDAH DIINPUT");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jMatkul))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SKS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kode)
                                    .addComponent(Matkul))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSks)
                                    .addComponent(txtMatkul)
                                    .addComponent(txtKode, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMahasiswa2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInsert)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFind)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClose)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jMatkul)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kode)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Matkul)
                    .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SKS)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jMahasiswa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        new FindMataKuliah().setVisible(true);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new MenuUtama(userLevel).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
    try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        String sql = "INSERT INTO mata_kuliah (kode_mk, nama_mk, sks) VALUES (?, ?, ?)";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        p.setString(1, txtKode.getText());
        p.setString(2, txtMatkul.getText());
        p.setString(3, txtSks.getText());
        
        p.executeUpdate();
        p.close();
        
        JOptionPane.showMessageDialog(this, "Data Mata Kuliah Berhasil Disimpan!");
        tampilkanData(); 
        kosongkanForm();
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
        java.sql.Connection c = config.Koneksi.getKoneksi();
        // Query SQL untuk mengupdate data berdasarkan kode_mk
        String sql = "UPDATE mata_kuliah SET nama_mk = ?, sks = ? WHERE kode_mk = ?";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        
        p.setString(1, txtMatkul.getText());
        p.setString(2, txtSks.getText());
        p.setString(3, txtKode.getText()); // Primary Key sebagai acuan
        
        p.executeUpdate();
        p.close();
        
        JOptionPane.showMessageDialog(this, "Data Mata Kuliah Berhasil Diperbarui!");
        tampilkanData(); // Refresh tabel agar perubahan kelihatan
        kosongkanForm();
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
    }   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int opsi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (opsi == JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection c = config.Koneksi.getKoneksi();
            String sql = "DELETE FROM mata_kuliah WHERE kode_mk = ?";
            java.sql.PreparedStatement p = c.prepareStatement(sql);
            
            p.setString(1, txtKode.getText());
            
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(this, "Data Mata Kuliah Telah Dihapus!");
            tampilkanData();
            kosongkanForm();
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMatkulMouseClicked
    int baris = tbMatkul.getSelectedRow();
    
    // Ambil data dari kolom tabel (0=kode, 1=nama, 2=sks)
    txtKode.setText(tbMatkul.getValueAt(baris, 0).toString());
    txtMatkul.setText(tbMatkul.getValueAt(baris, 1).toString());
    txtSks.setText(tbMatkul.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_tbMatkulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MataKuliah().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kode;
    private javax.swing.JLabel Matkul;
    private javax.swing.JLabel SKS;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jMahasiswa2;
    private javax.swing.JLabel jMatkul;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMatkul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables
}